# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        arguments: '-t ubuntu:$(Build.BuildId)'
    - script: |
        docker run -v $(pwd):/workspace ubuntu:$(Build.BuildId) make lint
      displayName: 'Run Linter and Type hints'
    - script: |
        docker run -v $(pwd):/workspace ubuntu:$(Build.BuildId) make test
      displayName: 'Run PyTest'
