version: '3.5'
services:
  cpu:
    container_name: project_name.cpu
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '28gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    working_dir: /workspace
    ports:
      - "8080:8080"
    tty: true
  gpu:
    container_name: project_name.gpu
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '28gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    ports:
      - "8080:8080"
    tty: true
