version: '3.5'
services:

  # macbook local環境
  mac:
    container_name: mizuta_env
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '12gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    working_dir: /workspace
    ports:
      - "8080:8080"
    tty: true

  # VM環境
  vm:
    container_name: mizuta_env
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '96gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ports:
      - "8080:8080"
    tty: true
