[tool.poetry]
name = "mizuta-env"
version = "0.1.0"
description = ""
authors = ["yuki mizuta"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<=3.9.16"
mkdocs = "^1.4.2"
mkdocs-material = "^9.0.3"
mkdocs-print-site-plugin = "^2.3.4"
htmlark = "^1.0.0"
mkdocs-minify-plugin = "^0.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^22.12.0"
mypy = "^0.991"
isort = "^5.11.4"
pytest = "^7.2.0"
ipykernel = "^6.19.4"

[tool.black]
line-length = 119

[tool.isort]
line_length = 119
profile = "black"

[tool.mypy]
ignore_missing_imports = true
