[tool.poetry]
name = "mizuta-env"
version = "0.1.0"
description = ""
authors = ["yuki mizuta"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<=3.9.16"
numpy = "<=1.23.3"
pandas = "^1.5.2"
opencv-python = "4.6.0.66"
mkdocs = "^1.4.2"
mkdocs-material = "^9.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
pyproject-flake8 = "^6.0.0"
flake8-bugbear = "^22.12.6"
pre-commit = "^2.21.0"
mypy = "^0.991"
isort = "^5.11.4"
pytest = "^7.2.0"
ipykernel = "^6.19.4"

[tool.flake8]
max-line-length = 119

[tool.black]
target-version = ['py39']
line-length = 119

[tool.isort]
line_length = 119
profile = "black"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
